# Generated by Django 5.1.4 on 2026-06-01 15:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='comment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('answer__isnull', True), ('question__isnull', False)), models.Q(('answer__isnull', False), ('question__isnull', True)), _connector='OR'), name='comment_has_exactly_one_target'),
        ),
    ]
